# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommender.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'recommender.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11recommender.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\"S\n\x12ProductInteraction\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x18\n\x10interaction_type\x18\x03 \x01(\t\"D\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1a\n\x12\x63urrent_product_id\x18\x02 \x01(\t\"G\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\"C\n\x16RecommendationResponse\x12)\n\x14recommended_products\x18\x01 \x03(\x0b\x32\x0b.pb.Product2\xa6\x01\n\x12RecommenderService\x12K\n\x12GetRecommendations\x12\x19.pb.RecommendationRequest\x1a\x1a.pb.RecommendationResponse\x12\x43\n\x11RecordInteraction\x12\x16.pb.ProductInteraction\x1a\x16.google.protobuf.EmptyB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommender_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_PRODUCTINTERACTION']._serialized_start=54
  _globals['_PRODUCTINTERACTION']._serialized_end=137
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=139
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=207
  _globals['_PRODUCT']._serialized_start=209
  _globals['_PRODUCT']._serialized_end=280
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=282
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=349
  _globals['_RECOMMENDERSERVICE']._serialized_start=352
  _globals['_RECOMMENDERSERVICE']._serialized_end=518
# @@protoc_insertion_point(module_scope)
